config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :create, :new] do
    resource :payment, only: [:create, :new]
  end
  root :to => "posts#index"

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :post
  attr_accessor :card_number, :card_verification
  serialize :params

  validates :first_name, :last_name, :card_type, :card_number, :card_verification, :card_expires_on, presence: true
  validate :validate_card

  def validate_card
    unless credit_card.valid?
      credit_card.errors.full_messages.each do |message|
        errors[:base] << message
      end
    end
  end

  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
      :brand              => card_type,
      :number             => card_number,
      :verification_value => card_verification,
      :month              => card_expires_on.try(:month),
      :year               => card_expires_on.try(:year),
      :first_name         => first_name,
      :last_name          => last_name
    )
  end

  def purchase
    amount = Money.new(Xantar::Application.config.post_amount, "USD").cents
    response = GATEWAY.purchase(amount, credit_card, :ip => "127.0.0.1")
    post.update_attribute(:purchased_at, Time.zone.now) if response.success?
    self.success = response.success?
    self.params = response.params
    self.save
    response.success?
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :payments
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def go_to path
    if request.xhr?
      render :js => "window.location = '#{path}'"
    else
      redirect_to path
    end
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :find_post

  def new
    @payment = Payment.new
  end

  def create
    @payment = @post.payments.build payment_params
    if @payment.valid?
      if @payment.purchase
        flash[:notice] = "Your successfully paid and your post has been submitted!"
        redirect_to root_path
      else
        flash[:alert] = "Ups something is went wrong! #{@payment.params['message']}"
        render :failure
      end
    else
      render :new
    end
  end

private

  def payment_params
    params.require(:payment).permit(:first_name, :last_name, :card_type, :card_number, :card_verification, :card_expires_on)
  end

  def find_post
    @post = Post.find params[:post_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def create
    @post = Post.new post_params
    if @post.save
      go_to new_post_payment_path(@post)
    else
      render :new
    end
  end

 private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def e params
    escape_javascript params
  end

end

app/helpers/form_helper.rb
module FormHelper
  ActionView::Helpers::FormBuilder.class_eval do
    include ActionView::Helpers::TagHelper
    include ActionView::Helpers::TextHelper
    include ActionView::Context

    def bs_text_field *input
      bs_field *input.unshift(:text_field)
    end

    def bs_text_area *input
      bs_field *input.unshift(:text_area)
    end

    def bs_select *input
      bs_field *input.unshift(:select)
    end

    def bs_field *input
      extra = input.last.is_a?(Hash) && input.last[:extra] ? input.pop[:extra] : {}
      column = input[1]
      errors = object.errors[column]
      content_tag(:div, class: "form-group #{'has-error' if errors.any?}") do
        content = self.label column, extra[:label], class: "control-label"
        content += self.send *input + [class: "form-control #{extra[:input_class]}"]
        content += content_tag :span, errors.join(", "), class: "help-block error"
        content
      end
    end

    def bs_checkbox(column, opts = {})
      extra = opts[:extra] ? opts[:extra] : {}
      content_tag(:div, class: "checkbox") do
        self.label column, class: "control-label" do
          self.check_box(column) + (extra[:label] || column.to_s.humanize)
        end
      end
    end


  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xantar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='container'>
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/payments/_form.html.erb
<%= form_for @payment, url: post_payment_path(@post) do |f| %>
<% f.object.errors[:base].each do |msg| %>
  <div class="alert alert-danger"><%= msg %></div>
<% end %>
<p><b>Amount: </b> <%= number_to_currency(Xantar::Application.config.post_amount) %></p>
  <%= f.bs_field :text_field, :first_name %>
  <%= f.bs_field :text_field, :last_name %>
  <%= f.bs_field :select, :card_type, [["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]], {}, extra: {input_class: 'input-30'} %>
  <%= f.bs_field :text_field, :card_number %>
  <p>test card: 4676949199749717</p>
  <%= f.bs_field :text_field, :card_verification, extra: {input_class: 'input-25'}%>
  <%= f.bs_field :date_select, :card_expires_on, {:discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :add_month_numbers => true}, extra: {input_class: 'dt_select'} %>

  <div class='form-group'>
    <%= f.submit "Process", class: 'btn btn-primary' %>
    <%= link_to "Cancel", root_path %>
  </div>
<% end %>

app/views/payments/failure.html.erb
<%= link_to "Try again", new_post_payment_path(@post) %> |
<%= link_to "Back to post list", root_path %>

app/views/payments/new.html.erb
<div class='row'>
  <div class='col-md-6'>
    <div class='panel panel-primary'>
      <div class='panel-heading'>
        <div class='panel-title'><h3>Make a payment to submit your post</h3></div>
      </div>
      <div class='panel-body'>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post ||= Post.new, remote: true do |f| %>
  <%= f.bs_text_area :content, extra: {label: "Post"} %>

  <div class='form-group'>
    <%= f.submit "Continue", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h2>Post yourself!</h2>

<%= render 'form' %>

<table class="table table-striped">
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td>
          <% if post.purchased_at %>
            <span class="label label-success">Submitted</span> at <%= post.purchased_at %>
          <% else %>
            <%= link_to "Submit now", new_post_payment_path(post) %>
          <% end %>
        </td>
        <td>Created at: <%= post.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.js.erb
$("form.new_post").replaceWith("<%= e render 'posts/form' %>")